name: Pedro Entringer
description: Um tanto quanto curioso
meta_description: "Pedro Entringer | Developer"

lang: pt-BR
markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: /
domain_name: 'https://pedroentringer.dev'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

permalink: /:categories/:title/

# Details for the RSS feed generator
url:            'https://pedroentringer.dev'
author:         'Pedro Entringer'
